/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class wildsheep_darknet_DarknetUtils */

#ifndef _Included_wildsheep_darknet_DarknetUtils
#define _Included_wildsheep_darknet_DarknetUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     wildsheep_darknet_DarknetUtils
* Method:    inference
* Signature: (Ljava/lang/String;)[Lwildsheep/darknet/Result;
*/
JNIEXPORT jobjectArray JNICALL Java_wildsheep_darknet_DarknetUtils_inference
(JNIEnv *, jobject, jstring);

/*
 * Class:     wildsheep_darknet_DarknetUtils
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_wildsheep_darknet_DarknetUtils_load
(JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     wildsheep_darknet_DarknetUtils
 * Method:    unload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_wildsheep_darknet_DarknetUtils_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
